yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list',
    ),
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth import views as auth_view

from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        views.LogOut.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        views.LogIn.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        auth_view.PasswordChangeView.as_view(
            template_name='users/password_change_form.html',
            success_url=reverse_lazy('users:password_change_done')
        ),
        name='password_change'
    ),
    path(
        'password_change/done',
        auth_view.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        auth_view.PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            success_url=reverse_lazy('users:password_reset_done')
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done',
        auth_view.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>',
        auth_view.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        auth_view.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='author_posts',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='group_posts'
    )

    def __str__(self) -> str:
        return self.text[:15]

    class Meta:
        ordering = ('-pub_date',)

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {
            'text': 'Текст поста',
            'group': 'Group',
        }
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings

from .models import Post, Group, User
from .forms import PostForm
from .utils import posts_paginator


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.all()
    page_obj = posts_paginator(request, posts, settings.OBJ_IN_PAGE)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.group_posts.all()
    page_obj = posts_paginator(request, posts, settings.OBJ_IN_PAGE)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    template = 'posts/profile.html'
    posts = user.author_posts.all()
    posts_count = posts.count()
    page_obj = posts_paginator(request, posts, settings.OBJ_IN_PAGE)
    context = {
        'page_obj': page_obj,
        'username': user,
        'posts_count': posts_count,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    context = {
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    template = 'posts/create_post.html'
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user)
    context = {
        'form': form,
        'is_edit': False,
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        post.save()
        return redirect('posts:post_detail', post.id)
    context = {
        'form': form,
        'is_edit': True,
        'post_id': post.id,
    }
    return render(request, template, context)

yatube/users/views.py
from django.views.generic import CreateView

from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную.
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'


class LogIn(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('post:index')
    template_name = 'users/login.html'


class LogOut(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('post:index')
    template_name = 'users/logout.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Тут я размещу информацию о себе, используя свои умения верстать.
  Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста. 
</p>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
{% load static %}
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
        YaTube
      {% endblock %}
    </title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
      {% block header %}
      {% endblock %}
    </header>
    <main>
      {% block content %}
        {% include 'index.html' %}
      {% endblock %}  
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>

yatube/templates/includes/footer.html
<class="border-top text-center py-3">
<!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
<!-- В дальнейшем тут будет создано полноценное меню -->
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
        <span style="color:red">Ya</span>tube</a>
    </a>
    <ul class="nav nav-pills">
      <li class="nav-item"> 
        <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
          href="{% url 'about:author' %}">
          Об авторе
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
          href="{% url 'about:tech' %}">
          Технологии
        </a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item"> 
        <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
          href="{% url 'posts:post_create' %}">
          Новая запись
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:password_change' %}">Изменить пароль</a>
      </li>
      <li>
        Пользователь: {{ user.username }}
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
      </li>
      {% else %}
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endwith %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock %}
{% block content %}  
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              {% if is_edit %}
                Редактировать запись
              {% else %}       
                Добавить запись
              {% endif %}      
            </div>
            <div class="card-body">
            {% load user_filters %} {# Загружаем фильтры #}
                {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endif %}      
              <form method="post">
                {% csrf_token %}
                {% for field in form %} 
                  <div class="form-group row my-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                        {% if field.field.required %}
                          <span class="required text-danger">*</span>
                        {% endif %}
                    </label>
                    {# К полю ввода добавляем атрибут class #}
                    {{ field|addclass:'form-control' }} 
                      {% if field.help_text %}
                        <small 
                          id="{{ field.id_for_label }}-help"
                          class="form-text text-muted"
                        >
                          {{ field.help_text|safe }}
                        </small>
                      {% endif %}
                  </div>
                {% endfor %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock%}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  {{ group.title }}
{% endblock %}
{% block header %} <h1> {{ group.title }} </h1> <p>{{ group.description }}</p> {% endblock %}
{% block content %}
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text|linebreaksbr }}</p>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
  </article>
  <!-- под последним постом нет линии -->
</div>  
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author %}">
          все посты пользователя
        </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text|linebreaksbr }}</p>
    <ul>
      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
    </ul>
    <ul>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">
          все записи группы
        </a>
      {% endif %}
    </ul>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group.title }}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                Все записи группы
              </a>
            </li>
            {% endif %}   
            <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.author_posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя {{ post.author.get_full_name }}
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>{{ post.text|linebreaksbr }}</p>
        </article>
        {% if user == post.author %}
          {% csrf_token %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id%}">
            Редактировать пост
          </a>
        {% endif %}
      </div> 
    </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  {{ user.get_full_name }} профайл пользователя
{% endblock %}
{% block content %}
  <h1>Все посты пользователя {{ user.get_full_name }} </h1>
  <h3>Всего постов: {{ posts_count }} </h3>
  {% for post in page_obj %}
    <article>
    <ul>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }} 
      </li>
    </ul>
    <p>{{ post.text|linebreaksbr }}</p>
    <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
    </article>
    {% if post.group %}      
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}      
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block title %}
  Изменение пароля
{% endblock %}
{% block content %}  
  <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action="{% url 'users:password_change' %}">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
  </main>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}
  Пароль изменен
{% endblock %}
{% block content %}
  <main>
    <div class="container py-5"> 
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Восстановление пароля завершено
            </div>
            <div class="card-body">
              <p>Ваш пароль был сохранен. Используйте его для входа</p>
              <a href="{% url 'users:login' %}">войти</a>
            </div> 
          </div> 
        </div>
      </div> 
    </div>
  </main>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
{% load user_filters %}

{% if validlink %}

  <main>
    <div class="container py-5"> 
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Введите новый пароль
            </div>
            <div class="card-body">
              <form method="post" action="{% url 'users:password_reset_confirm' %}">
                {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  <label for="id_new_password1">
                    Новый пароль        
                    <span class="required text-danger">*</span>        
                  </label>    
                  <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
                  <small id="id_new_password1-help" class="form-text text-muted">
                    <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                  </small>      
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_new_password2">
                    Подтверждение нового пароля        
                    <span class="required text-danger">*</span>        
                  </label>    
                  <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
                </div>
                <div class="col-md-6 offset-md-4">
                  <button type="submit" class="btn btn-primary">
                    Назначить новый пароль
                  </button>
                </div>
              </form>
            </div> <!-- card body -->
          </div> <!-- card -->
        </div> <!-- col -->
      </div> <!-- row -->
    </div>
{% else %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Ошибка</div>
        <div class="card-body">
          <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endif %}
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block title %}
  Сброс пароля
{% endblock %}
{% block content %}
  <main>
    <div class="container py-5"> 
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
            </div>
            <div class="card-body"> 
              <form method="post" action="{% url 'users:password_reset' %}">
                {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  <label for="id_email">
                    Адрес электронной почты
                    <span class="required text-danger">*</span>
                  </label>    
                  <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
                </div>
                <div class="col-md-6 offset-md-4">
                  <button type="submit" class="btn btn-primary">
                    Сбросить пароль
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </main>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}